#!/bin/env bash
function information () {
   echo ''
   echo '------------------'
   echo 'Information from your command:'
   echo '------------------'
   
}
function greenColor () {
    GREEN="\033[0;32m"
    ENDCOLOR="\033[0m"
    echo -e "${GREEN} $* \t ${ENDCOLOR}"
    
}

function redColor () {
    RED="\e[31m"
    ENDCOLOR="\e[0m"
    echo -e "${RED} $* \t ${ENDCOLOR}"
}
echo ''
echo 'What you want to check?'
echo 'Select appropriate option:'
echo '1) Check hostname'
echo '2) Check kernel version'
echo '3) Check ip address'
echo '4) Check memory'
echo '5) Check listening port'
echo '6) Check space in your home directory'
echo '--------------------------'
read -p "Write here your number: " choseOption
echo '--------------------------'
echo ''

while true
do
   case $choseOption in

   1)  
        information
        hostInfo=${HOSTNAME}
        greenColor 'Hostname:' $hostInfo       
        bash check_information_about_system
         ;;
        
   2)
        information
        kernelVer=$(uname -a | awk '{ print $3}')
        greenColor 'Kernel:' $kernelVer
        bash check_information_about_system
         ;;
         
   3)
        information
        greenColor "Network adapters and their IP:"
        redColor "NIC \t IP"
        IPAdd=$(ip a | grep 'eth[0-9]' | awk 'FNR == 2 { print $2 }')
        NetAdapter=$(ip a | grep 'eth[0-10]' | awk 'FNR == 1 { print $2 }')
        greenColor $NetAdapter "\t" $IPAdd 
        bash check_information_about_system
         ;;
  
   4) information
        greenColor "Free memory:"  
        FreeMem=$(free -hm | awk ' FNR == 2 { print $7 }')
        greenColor $FreeMem
        echo "============="
        redColor "Used memory:"
        UsedMem=$(free -hm | awk ' FNR == 2 { print $3 }')
        redColor $UsedMem
        bash check_information_about_system
         ;;
   5) information
        greenColor "Protocol State Local Address:Port  Peer Address:PortProcess"
        listeningPorts=$( ss -ntau | grep "LISTEN" | awk ' { print $1 " | " $2 " | " $5 " | " $6 } ')
        if [ -z "$listeningPorts" ]
        then
           redColor "You don't have listening port"
           break
        else   
        redColor $listeningPorts
        break
        bash check_information_about_system
        fi
         ;;
   6) information
        spaceHO=$(du -d 0 -h ~)
        greenColor "Your home directory has:" $spaceHO
        bash check_information_about_system
         ;;
   *) 
      redColor "Wrong number!!"
      bash check_information_about_system 
      ;;

   esac
done
